### ISSUE TITLE
lightdm_greeter_error: Unable to determine socket to daemon

### ISSUE THREAD

**Issue by ghost** [Antergos/lightdm-webkit2-greeter#174]
Hello, 

Specs:
OS: ubuntu 18.04
WM: i3-gaps

I have managed to install successfully through downloading and manually installing as instructed in the wiki and I have all the required dependencies and then I included `X-LightDM-Allow-Greeter=true` in my desktop file.

when I try to start it using `web-greeter` I get this error:
`
2018-09-27 13:16:07 [ DEBUG ] objects - objects.py:124 : _setup_logger | Logger is ready.
2018-09-27 13:16:07 [ DEBUG ] app - app.py:57 : _wh_load_config | Try load config using key: WebGreeter
2018-09-27 13:16:07 [ DEBUG ] window - window.py:78 : _initialize | Initializing Main Window
2018-09-27 13:16:07 [ DEBUG ] __main__ - __main__.py:64 : __init__ | Web Greeter started.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/web-greeter/__main__.py", line 110, in <module>
  File "/usr/bin/web-greeter/__main__.py", line 65, in __init__
  File "/usr/bin/web-greeter/bridge/Greeter.py", line 73, in __init__
gi.repository.GLib.Error: lightdm_greeter_error: Unable to determine socket to daemon (1)
` 
I have enabled logging and the log files are empty.

if there's any more info you need I'd be happy to provide it.

Thanks in advance.

**Comment by MaukWM** [comment]
Hey, I'm running Ubuntu 18.04 with i3 (not gaps) and I'm getting exactly the same error!
