### ISSUE TITLE
ModuleNotFoundError: No module named 'whither'

### ISSUE THREAD

**Issue by ahloiscreamo** [Antergos/lightdm-webkit2-greeter#182]
1.- i install whither using pip ,they installed succesfully but when i log out and log in back i issues 'web-greeter' on terminal and it out put missing module whither.
2- i installed from source file but same problem missing module.

terminal output 

```
~
❯ web-greeter
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/web-greeter/__main__.py", line 37, in <module>
ModuleNotFoundError: No module named 'whither'

~
❯
```

**Comment by lots0logs** [comment]
Try installing it using pip instead of from source. That should work.
